version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 515517371214.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t sast .
      - docker tag sast:latest 515517371214.dkr.ecr.us-east-1.amazonaws.com/sast:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 515517371214.dkr.ecr.us-east-1.amazonaws.com/sast:latest
      - echo Writing image definitions file...
      - printf '[{"name":"sast","imageUri":"515517371214.dkr.ecr.us-east-1.amazonaws.com/sast:latest"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
